name: Construcci贸n y despliegue de una aplicaci贸n MVC a Azure

env:
  AZURE_WEBAPP_NAME: appblazor2024123456  # Aqui va el nombre de su aplicaci贸n
  AZURE_WEBAPP_PACKAGE_PATH: '.'          # Es la ruta de destino
  DOTNET_VERSION: '8'                     # la versi贸n de .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Probando az cli
        run: | 
          az login -u ${{ secrets.AWA_USERNAME }} -p ${{ secrets.AWA_PASSWORD }} --only-show-errors
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3