name: Construcción Infrastructura en Azure

env:
  AZURE_WEBAPP_NAME: appblazor2024123456  # Aqui va el nombre de su aplicación
  AZURE_WEBAPP_PACKAGE_PATH: '.'          # Es la ruta de destino
  DOTNET_VERSION: '8'                     # la versión de .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login azure
        run: | 
          az login -u ${{ secrets.AWA_USERNAME }} -p ${{ secrets.AWA_PASSWORD }} --only-show-errors
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
    #   - name: Terraform Fmt
    #     run: cd Infra && terraform fmt -check
      - name: Terraform Init
        run: cd Infra && terraform init 
        #-backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}"
      - name: Terraform Validate
        run: cd Infra && terraform validate -no-color
    #   - name: tfsec
    #     uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
    #     with:
    #       tfsec_args: --soft-fail
    #       github_token: ${{ github.token }}
      - name: Terraform Plan
        run: cd Infra && terraform plan -no-color -out main.tfplan

      - name: Create String Output
        id: tf-plan-string
        run: |
            TERRAFORM_PLAN=$(terraform show -no-color main.tfplan)

            delimiter="$(openssl rand -hex 8)"
            echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
            echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
            echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo '```terraform' >> $GITHUB_OUTPUT
            echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
            echo '```' >> $GITHUB_OUTPUT
            echo "</details>" >> $GITHUB_OUTPUT
            echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
